# Generated by Django 3.0.1 on 2020-01-09 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='miss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('gender', models.TextField()),
                ('age', models.TextField()),
                ('height', models.TextField()),
                ('address', models.TextField()),
                ('missing_location', models.TextField()),
                ('contact_number', models.TextField()),
                ('email_id', models.TextField()),
            ],
        ),
    ]
