# Generated by Django 3.0.1 on 2020-01-17 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='miss',
            name='photo',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/'),
        ),
        migrations.AlterField(
            model_name='miss',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='miss',
            name='contact_number',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='miss',
            name='email_id',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='miss',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=2),
        ),
        migrations.AlterField(
            model_name='miss',
            name='height',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='miss',
            name='missing_location',
            field=models.CharField(choices=[('Chu', 'Churchgate'), ('MarL', 'Marine Line'), ('ChaR', 'Charni Road'), ('GraR', 'Grant Road'), ('MumC', 'Mumbai Central'), ('Mah', 'Mahalaxmi'), ('LowP', 'Lowerparel'), ('ElpR', 'Elphinstone Road'), ('Dad', 'Dadar'), ('MatR', 'Matunga Road'), ('MahJ', 'Mahim Junction'), ('Ban', 'Bandra'), ('KhaR', 'Khar Road'), ('San', 'Santacruz'), ('VilP', 'Vile Parle'), ('And', 'Andheri'), ('Jog', 'Jogeshwari'), ('RamM', 'Ram Mandir'), ('Gor', 'Goregaon'), ('Mal', 'Malad'), ('Kan', 'Kandivali'), ('Bor', 'Borivali'), ('Dah', 'Dahisar'), ('MCST', 'Mumbai CST'), ('Mbun', 'Masjid bunder'), ('SanR', 'Sandhurst Road'), ('By', 'Byculla'), ('Chi', 'Chinchpokli'), ('Cur', 'CurreyRoad'), ('Prl', 'Parel'), ('Mat', 'Matunga'), ('Si', 'Sion'), ('Ku', 'Kurla'), ('Vid', 'Vidyavihar'), ('Gha', 'Ghatkopar'), ('Vik', 'Vikroli'), ('Kan', 'Kanjurmarg'), ('Bha', 'Bhandup'), ('Nah', 'Nahur'), ('Mul', 'Mulund'), ('Tha', 'Thane')], default='Chu', max_length=4),
        ),
        migrations.AlterField(
            model_name='miss',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
