# Generated by Django 3.0.1 on 2020-01-09 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='crime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('gender', models.TextField()),
                ('age', models.TextField()),
                ('height', models.TextField()),
                ('location', models.TextField()),
                ('date', models.TextField()),
                ('time', models.TextField()),
                ('crime', models.TextField()),
            ],
        ),
    ]
