# Generated by Django 3.0.1 on 2020-01-16 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crime',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=2),
        ),
    ]
