# Generated by Django 3.0.1 on 2020-01-17 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminal', '0002_auto_20200116_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crime',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='crime',
            name='height',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='crime',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
