# Generated by Django 3.0.1 on 2020-01-17 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminal', '0003_auto_20200117_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crime',
            name='date',
        ),
        migrations.RemoveField(
            model_name='crime',
            name='time',
        ),
        migrations.AddField(
            model_name='crime',
            name='photo',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/'),
        ),
        migrations.AlterField(
            model_name='crime',
            name='height',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
