# Generated by Django 3.0.1 on 2020-01-17 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminal', '0004_auto_20200117_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crime',
            name='crime',
            field=models.CharField(choices=[('MR', 'Murder'), ('BM', 'Blackmail'), ('CA', 'Child Abuse'), ('DD', 'Drunk Driver'), ('E', 'Extortion'), ('F', 'Fraud'), ('PP', 'Pickpocketing'), ('R', 'Robbery'), ('T', 'Threat')], default='MR', max_length=2),
        ),
        migrations.AlterField(
            model_name='crime',
            name='location',
            field=models.CharField(choices=[('Chu', 'Churchgate'), ('MarL', 'Marine Line'), ('ChaR', 'Charni Road'), ('GraR', 'Grant Road'), ('MumC', 'Mumbai Central'), ('Mah', 'Mahalaxmi'), ('LowP', 'Lowerparel'), ('ElpR', 'Elphinstone Road'), ('Dad', 'Dadar'), ('MatR', 'Matunga Road'), ('MahJ', 'Mahim Junction'), ('Ban', 'Bandra'), ('KhaR', 'Khar Road'), ('San', 'Santacruz'), ('VilP', 'Vile Parle'), ('And', 'Andheri'), ('Jog', 'Jogeshwari'), ('RamM', 'Ram Mandir'), ('Gor', 'Goregaon'), ('Mal', 'Malad'), ('Kan', 'Kandivali'), ('Bor', 'Borivali'), ('Dah', 'Dahisar'), ('MCST', 'Mumbai CST'), ('Mbun', 'Masjid bunder'), ('SanR', 'Sandhurst Road'), ('By', 'Byculla'), ('Chi', 'Chinchpokli'), ('Cur', 'CurreyRoad'), ('Prl', 'Parel'), ('Mat', 'Matunga'), ('Si', 'Sion'), ('Ku', 'Kurla'), ('Vid', 'Vidyavihar'), ('Gha', 'Ghatkopar'), ('Vik', 'Vikroli'), ('Kan', 'Kanjurmarg'), ('Bha', 'Bhandup'), ('Nah', 'Nahur'), ('Mul', 'Mulund'), ('Tha', 'Thane')], default='Mul', max_length=4),
        ),
    ]
